"""Added reputation game stats tables

Revision ID: 87318da2b4a9
Revises: 86e052113f8e
Create Date: 2019-01-26 11:29:15.224622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87318da2b4a9'
down_revision = '86e052113f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reputation_community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corrupted_observations', sa.Boolean(), nullable=False),
    sa.Column('number_of_onlookers', sa.Integer(), nullable=True),
    sa.Column('length_of_generations', sa.Integer(), nullable=True),
    sa.Column('mutation_chance', sa.Float(), nullable=True),
    sa.Column('cooperation_rate', sa.Integer(), nullable=True),
    sa.Column('social_activeness', sa.Integer(), nullable=True),
    sa.Column('positivity_of_gossip', sa.Integer(), nullable=True),
    sa.Column('fitness', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reputation_strategy',
    sa.Column('strategy_name', sa.String(), nullable=False),
    sa.Column('strategy_options', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('strategy_name', 'strategy_options')
    )
    op.create_table('reputation_generation',
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_point', sa.Integer(), nullable=True),
    sa.Column('end_point', sa.Integer(), nullable=True),
    sa.Column('cooperation_rate', sa.Integer(), nullable=True),
    sa.Column('social_activeness', sa.Integer(), nullable=True),
    sa.Column('positivity_of_gossip', sa.Integer(), nullable=True),
    sa.Column('fitness', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['reputation_community.id'], ),
    sa.PrimaryKeyConstraint('community_id', 'id')
    )
    op.create_table('reputation_player',
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('cooperation_rate', sa.Integer(), nullable=True),
    sa.Column('social_activeness', sa.Integer(), nullable=True),
    sa.Column('positivity_of_gossip', sa.Integer(), nullable=True),
    sa.Column('fitness', sa.Integer(), nullable=True),
    sa.Column('strategy_name', sa.String(), nullable=True),
    sa.Column('strategy_options', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['reputation_community.id'], ),
    sa.ForeignKeyConstraint(['generation_id'], ['reputation_generation.id'], ),
    sa.ForeignKeyConstraint(['strategy_name'], ['reputation_strategy.strategy_name'], ),
    sa.ForeignKeyConstraint(['strategy_options'], ['reputation_strategy.strategy_options'], ),
    sa.PrimaryKeyConstraint('generation_id', 'community_id')
    )
    op.create_table('reputation_action',
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timepoint', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('INTERACTION', 'GOSSIP', 'IDLE', name='actiontype'), nullable=False),
    sa.Column('gossiper', sa.Integer(), nullable=True),
    sa.Column('about', sa.Integer(), nullable=True),
    sa.Column('recipient', sa.Integer(), nullable=True),
    sa.Column('gossip', sa.Enum('POSITIVE', 'NEGATIVE', name='gossipcontent'), nullable=True),
    sa.Column('donor', sa.Integer(), nullable=True),
    sa.Column('onlookers', sa.ARRAY(sa.Integer(), as_tuple=ForeignKey('reputation_player.id')), nullable=True),
    sa.Column('action', sa.Enum('COOPERATE', 'DEFECT', name='interactioncontent'), nullable=True),
    sa.ForeignKeyConstraint(['about'], ['reputation_player.id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['reputation_community.id'], ),
    sa.ForeignKeyConstraint(['donor'], ['reputation_player.id'], ),
    sa.ForeignKeyConstraint(['generation_id'], ['reputation_generation.id'], ),
    sa.ForeignKeyConstraint(['gossiper'], ['reputation_player.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['reputation_player.id'], ),
    sa.ForeignKeyConstraint(['recipient'], ['reputation_player.id'], ),
    sa.PrimaryKeyConstraint('generation_id', 'community_id', 'player_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reputation_action')
    op.drop_table('reputation_player')
    op.drop_table('reputation_generation')
    op.drop_table('reputation_strategy')
    op.drop_table('reputation_community')
    # ### end Alembic commands ###
