import unittest
from app import app, db
from app.models import Strategy, Game, Agent, Action, Round


class GameModelCase(unittest.TestCase):
    def setUp(self):
        app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite://'
        db.create_all()

    def tearDown(self):
        db.session.remove()
        db.drop_all()

    def test_get_interaction_history(self):
        game1 = Game()
        game2 = Game()
        db.session.add(game1)
        db.session.add(game2)
        db.session.commit()
        strategy1 = Strategy(name='strat1', description='hello1')
        strategy2 = Strategy(name='strat2', description='hello2')
        strategy3 = Strategy(name='strat3', description='hello3')
        agent0 = Agent(strategy_name='strat1', game_id=1)
        agent1 = Agent(strategy_name='strat3', game_id=1)
        agent2 = Agent(strategy_name='strat1', game_id=2)
        agent3 = Agent(strategy_name='strat2', game_id=2)
        round1game1 = Round(game_id=1)
        round2game1 = Round(game_id=1)
        round3game1 = Round(game_id=1)
        round4game1 = Round(game_id=1)
        round1game2 = Round(game_id=2)
        round2game2 = Round(game_id=2)
        round3game2 = Round(game_id=2)
        db.session.add(strategy1)
        db.session.add(strategy2)
        db.session.add(strategy3)
        db.session.add(agent0)
        db.session.add(agent1)
        db.session.add(agent2)
        db.session.add(agent3)
        db.session.add(round3game1)
        db.session.add(round4game1)
        db.session.add(round1game2)
        db.session.add(round2game2)
        db.session.add(round3game2)
        db.session.add(round2game1)
        db.session.add(round1game1)
        db.session.commit()
        agent0round0game0 = Action(round_id=1, agent_id=1, cooperates=True)
        agent0round1game0 = Action(round_id=2, agent_id=1, cooperates=True)
        agent0round2game0 = Action(round_id=3, agent_id=1, cooperates=False)
        agent0round3game0 = Action(round_id=4, agent_id=1, cooperates=True)
        agent1round0game0 = Action(round_id=1, agent_id=2, cooperates=False)
        agent1round1game0 = Action(round_id=2, agent_id=2, cooperates=True)
        agent1round2game0 = Action(round_id=3, agent_id=2, cooperates=True)
        agent1round3game0 = Action(round_id=4, agent_id=2, cooperates=False)
        agent2round0game1 = Action(round_id=1, agent_id=3, cooperates=True)
        agent2round1game1 = Action(round_id=2, agent_id=3, cooperates=True)
        agent2round2game1 = Action(round_id=3, agent_id=3, cooperates=False)
        agent3round0game1 = Action(round_id=1, agent_id=4, cooperates=False)
        agent3round1game1 = Action(round_id=2, agent_id=4, cooperates=True)
        agent3round2game1 = Action(round_id=3, agent_id=4, cooperates=True)
        db.session.add(agent0round0game0)
        db.session.add(agent0round1game0)
        db.session.add(agent0round2game0)
        db.session.add(agent0round3game0)
        db.session.add(agent1round0game0)
        db.session.add(agent1round1game0)
        db.session.add(agent1round2game0)
        db.session.add(agent1round3game0)
        db.session.add(agent2round0game1)
        db.session.add(agent2round1game1)
        db.session.add(agent2round2game1)
        db.session.add(agent3round0game1)
        db.session.add(agent3round1game1)
        db.session.add(agent3round2game1)
        db.session.commit()
        print(game2.get_interaction_history().all())
        print(game1.get_interaction_history().all())
        print(Round.query.all())
