def strat_2(db, strategy):
    db.session.add(strategy(name="Tit-For-Tat", description='Start by cooperating, then copy the last turn from the other agent'))
    db.session.add(strategy(name="Grudger", description='Start by cooperating, if the other agent defects switch and defect from then on'))
    db.session.add(strategy(name="Always Cooperate", description='Cooperate no matter what'))
    db.session.add(strategy(name="Always Defect", description='Defect no matter what'))
    db.session.commit()


def games_2(db, game, agent, action, game_agent_association):
    game1 = game()
    game2 = game()
    game3 = game()
    agent1 = agent(strategy_name='Tit-For-Tat')
    agent2 = agent(strategy_name='Grudger')
    agent3 = agent(strategy_name='Always Cooperate')
    agent4 = agent(strategy_name='Always Defect')
    agent1game1 = game_agent_association(game_id=1, agent_id=1)
    agent2game1 = game_agent_association(game_id=1, agent_id=2)
    agent3game2 = game_agent_association(game_id=2, agent_id=3)
    agent4game2 = game_agent_association(game_id=2, agent_id=4)
    agent2game3 = game_agent_association(game_id=3, agent_id=2)
    agent4game3 = game_agent_association(game_id=3, agent_id=4)
    action1agent1game1 = action(game_id=1, round_num=1, agent_id=1, cooperates=True)
    action1agent2game1 = action(game_id=1, round_num=1, agent_id=2, cooperates=True)
    action2agent1game1 = action(game_id=1, round_num=2, agent_id=1, cooperates=True)
    action2agent2game1 = action(game_id=1, round_num=2, agent_id=2, cooperates=True)
    action3agent1game1 = action(game_id=1, round_num=3, agent_id=1, cooperates=True)
    action3agent2game1 = action(game_id=1, round_num=3, agent_id=2, cooperates=True)
    action4agent1game1 = action(game_id=1, round_num=4, agent_id=1, cooperates=True)
    action4agent2game1 = action(game_id=1, round_num=4, agent_id=2, cooperates=True)
    action1agent3game2 = action(game_id=2, round_num=1, agent_id=3, cooperates=True)
    action1agent4game2 = action(game_id=2, round_num=1, agent_id=4, cooperates=False)
    action2agent3game2 = action(game_id=2, round_num=2, agent_id=3, cooperates=True)
    action2agent4game2 = action(game_id=2, round_num=2, agent_id=4, cooperates=False)
    action3agent3game2 = action(game_id=2, round_num=3, agent_id=3, cooperates=True)
    action3agent4game2 = action(game_id=2, round_num=3, agent_id=4, cooperates=False)
    action4agent3game2 = action(game_id=2, round_num=4, agent_id=3, cooperates=True)
    action4agent4game2 = action(game_id=2, round_num=4, agent_id=4, cooperates=False)
    action1agent2game3 = action(game_id=3, round_num=1, agent_id=2, cooperates=True)
    action1agent4game3 = action(game_id=3, round_num=1, agent_id=4, cooperates=False)
    action2agent2game3 = action(game_id=3, round_num=2, agent_id=2, cooperates=False)
    action2agent4game3 = action(game_id=3, round_num=2, agent_id=4, cooperates=False)
    action3agent2game3 = action(game_id=3, round_num=3, agent_id=2, cooperates=False)
    action3agent4game3 = action(game_id=3, round_num=3, agent_id=4, cooperates=False)
    action4agent2game3 = action(game_id=3, round_num=4, agent_id=2, cooperates=False)
    action4agent4game3 = action(game_id=3, round_num=4, agent_id=4, cooperates=False)
    db.session.add(game1)
    db.session.add(game2)
    db.session.add(game3)
    db.session.add(agent1)
    db.session.add(agent2)
    db.session.add(agent3)
    db.session.add(agent4)
    db.session.add(agent1game1)
    db.session.add(agent2game1)
    db.session.add(agent3game2)
    db.session.add(agent4game2)
    db.session.add(agent2game3)
    db.session.add(agent4game3)
    db.session.add(action1agent1game1)
    db.session.add(action1agent2game1)
    db.session.add(action2agent1game1)
    db.session.add(action2agent2game1)
    db.session.add(action3agent1game1)
    db.session.add(action3agent2game1)
    db.session.add(action4agent1game1)
    db.session.add(action4agent2game1)
    db.session.add(action1agent3game2)
    db.session.add(action1agent4game2)
    db.session.add(action2agent3game2)
    db.session.add(action2agent4game2)
    db.session.add(action3agent3game2)
    db.session.add(action3agent4game2)
    db.session.add(action4agent3game2)
    db.session.add(action4agent4game2)
    db.session.add(action1agent2game3)
    db.session.add(action1agent4game3)
    db.session.add(action2agent2game3)
    db.session.add(action2agent4game3)
    db.session.add(action3agent2game3)
    db.session.add(action3agent4game3)
    db.session.add(action4agent2game3)
    db.session.add(action4agent4game3)
    db.session.commit()










