check_timepoints(Timepoints):-
	holds_at(interaction_timepoints(agent(strategy("Standing Discriminator", _, ["trusting"]), community(0), generation(community(0), 0), 5),
			agent(strategy("defector", _, []), community(0), generation(community(0), 0), 6))=Timepoints, 2).
	writeln(Timepoints),
	holds_at(interaction_timepoints(agent(strategy("Standing Discriminator", _, ["trusting"]), community(0), generation(community(0), 0), 5),
		agent(strategy("defector", _, []), community(0), generation(community(0), 0), 6))=Timepoints1, 3),
	writeln(Timepoints1),
	holds_at(interaction_timepoints(agent(strategy("Standing Discriminator", _, ["trusting"]), community(0), generation(community(0), 0), 5),
		agent(strategy("defector", _, []), community(0), generation(community(0), 0), 6))=Timepoints2, 4),
	writeln(Timepoints2),
	holds_at(interaction_timepoints(agent(strategy("Standing Discriminator", _, ["trusting"]), community(0), generation(community(0), 0), 5),
		agent(strategy("defector", _, []), community(0), generation(community(0), 0), 6))=Timepoints3, 5),
	writeln(Timepoints3),
	holds_at(interaction_timepoints(agent(strategy("defector", _, []), community(0), generation(community(0), 0), 6),
		agent(strategy("cooperator", "desc", []), community(0), generation(community(0), 0), 7))=Timepoints7, 4),
	writeln(Timepoints7),
	holds_at(interaction_timepoints(agent(strategy("cooperator", _, []), community(0), generation(community(0), 0), 7),
		agent(strategy("defector", "desc", []), community(0), generation(community(0), 0), 6))=Timepoints8, 6),
	writeln(Timepoints8),
	holds_at(interaction_timepoints(agent(strategy("cooperator", _, []), community(0), generation(community(0), 0), 7),
		agent(strategy("Standing Discriminator", "desc", ["trusting"]), community(0), generation(community(0), 0), 5))=Timepoints10, 7),
	writeln(Timepoints10),
	holds_at(interaction_timepoints(agent(strategy("Standing Discriminator", _, ["trusting"]), community(0), generation(community(0), 0), 8),
		agent(strategy("Standing Discriminator", "desc", ["trusting"]), community(0), generation(community(0), 0), 5))=Timepoints12, 8),
	writeln(Timepoints12).
